function luaQuote(s) {
  return '"' + String(s).replace(/[\\"\x00-\x1f\x7f]/g, (char) => {
    if (char === "\\") return "\\\\";
    if (char === '"') return '\\"';
    return `\\${char.charCodeAt(0).toString().padStart(3, "0")}`;
  }) + '"';
}

function luaComment(s) {
  return String(s).replace(/[\x00-\x1f\x7f]/g, " ");
}

function compareUtf8(a, b) {
  return Buffer.compare(Buffer.from(a, "utf8"), Buffer.from(b, "utf8"));
}

const LUA_RESERVED = new Set([
  "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
  "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true",
  "until", "while",
]);

function luaKey(key) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !LUA_RESERVED.has(key)
    ? key
    : `[${luaQuote(key)}]`;
}

function luaDbValue(value, key) {
  if (typeof value === "string") return luaQuote(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  throw new Error(`invalid db value for '${key}'`);
}

function luaNumber(value, what) {
  const number = Number(value);
  if (!Number.isFinite(number)) throw new Error(`invalid ${what}`);
  return number;
}

// A hyphen (or other non-identifier character) in the addon name is valid
// in the name itself but would produce an odd SavedVariables global if
// concatenated as-is (e.g. "RGX-Hello" -> "RGX-HelloDB"). Strip anything
// that isn't a safe Lua identifier character for the auto-derived default,
// matching the precedent set by RGX-Hello's own hand-written core.lua
// (dbName = "RGXHelloDB").
function defaultDbName(name) {
  return name.replace(/[^A-Za-z0-9_]/g, "") + "DB";
}

function generateAddonLua(spec) {
  const name = spec.name;
  const dbName = spec.dbName || defaultDbName(name);
  const needsExplicitDbName = Boolean(spec.dbName) || /[^A-Za-z0-9_]/.test(name);
  const out = [];
  out.push(`-- ${luaComment(name)}.lua ? generated by rgx-mcp against the RGX Simplicity Contract`);
  out.push(`-- TOC needs: ## RequiredDeps: RGX-Framework` +
    (spec.db ? `  and  ## SavedVariables: ${luaComment(dbName)}` : ""));
  out.push(`RGXAddon ${luaQuote(name)} {`);
  if (needsExplicitDbName && spec.db) out.push(`    dbName  = ${luaQuote(dbName)},`);
  out.push(`    slash   = ${luaQuote(spec.slash ?? name.toLowerCase())},`);
  if (spec.minimap) out.push(`    minimap = true,`);
  if (spec.db) {
    const entries = Object.entries(spec.db)
      .map(([k, v]) => `${luaKey(k)} = ${luaDbValue(v, k)}`)
      .join(", ");
    out.push(`    db      = { ${entries} },`);
  }
  const timers = Object.entries(spec.every ?? {}).sort(([a], [b]) => compareUtf8(a, b));
  if (timers.length) {
    out.push(`    every   = {`);
    for (const [timerName, seconds] of timers) {
      const secs = luaNumber(seconds, `timer '${timerName}' seconds`);
      if (secs <= 0) throw new Error(`timer '${timerName}' seconds must be positive`);
      out.push(`        ${luaKey(timerName)} = { ${secs}, function(self, timer)`);
      out.push(`            -- Run ${luaComment(timerName)} every ${secs} second${secs === 1 ? "" : "s"}.`);
      out.push(`        end },`);
    }
    out.push(`    },`);
  }
  const controls = [];
  for (const t of spec.toggles ?? []) {
    controls.push(`            { toggle = ${luaQuote(t)} },`);
  }
  for (const s of spec.sliders ?? []) {
    const parts = [`slider = ${luaQuote(s.key)}`];
    if (s.label) parts.push(`label = ${luaQuote(s.label)}`);
    parts.push(
      `min = ${luaNumber(s.min ?? 0, `slider '${s.key}' min`)}`,
      `max = ${luaNumber(s.max ?? 100, `slider '${s.key}' max`)}`
    );
    if (s.suffix) parts.push(`suffix = ${luaQuote(s.suffix)}`);
    if (s.valueDisplay) parts.push(`valueDisplay = ${luaQuote(s.valueDisplay)}`);
    if (s.progress !== undefined) parts.push(`progress = ${Boolean(s.progress)}`);
    controls.push(`            { ${parts.join(", ")} },`);
  }
  if (controls.length || spec.columns !== undefined) {
    out.push(`    options = {`);
    if (spec.columns !== undefined) {
      const columns = luaNumber(spec.columns, "columns");
      if (!Number.isInteger(columns)) throw new Error("columns must be an integer");
      out.push(`        columns = ${columns},`);
    }
    out.push(`        General = {`);
    out.push(...controls);
    out.push(`        },`);
    out.push(`    },`);
  }
  out.push(`    welcome = ${luaQuote(`loaded ? /${spec.slash ?? name.toLowerCase()} for options`)},`);
  out.push(`}`);
  return out.join("\n");
}


export { generateAddonLua };
